baseURL = 'https://ptrpl4.github.io/blog-project/'
defaultContentLanguage = 'ru'
languageCode = 'ru-ru'
title = 'wtf-is-going-on'
theme = [ 'PaperMod' ]

[params]
    subtitle = 'Never asked for this'
    dateFormat = '2006-01-02
    author = 'Pyotr V'
    twitter = 'x'
    telegram = 'x'
    instagram = 'x'
    github = 'x'

[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'Видеоигры'
    url = 'categories/видеоигры'
    weight = 1

[services]
[services.googleAnalytics]
    ID = 'G-4KFQHHFCTF'