baseURL = 'https://ptrpl4.github.io/blog-project/'
defaultContentLanguage = 'ru'
languageCode = 'ru-ru'
title = 'wtf-is-going-on'
theme = [ 'PaperMod' ]

[menus]
    [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
    
    [[menus.main]]
    name = 'Видеоигры'
    url = 'categories/видеоигры'
    weight = 1

[params]
subtitle = 'Never asked for this'
dateFormat = '2006-01-02'
author = 'Pyotr V'
twitter = 'x'
telegram = 'x'
instagram = 'x'
github = 'x'
disableScrollToTop = false
footer.hideCopyright = true

    [params.homeInfoParams]
    Title = "🫥"
    Content = "Just another one website"

    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/ptrpl4"

[services]
    [services.googleAnalytics]
    ID = 'G-4KFQHHFCTF'
